################# https://www.ahbl.org/rspamd

AHBL_SPAMSIGNS_BODY {
  type = "content";
  filter = "oneline";
  map = "https://downloads.ahbl.org/rspamd/ahbl-spamsigns-body.map.zst";
  regexp = true;
  description = "AHBL: Spam signs in body";
}

AHBL_SPAMSIGNS_CS {
  type = "content";
  filter = "oneline";
  map = "https://downloads.ahbl.org/rspamd/ahbl-spamsigns-contactsocial.map.zst";
  regexp = true;
  description = "AHBL: Contact / social spam signs in body";
}

AHBL_SPAMSIGNS_SUBJECT {
  type = "header";
  header = "Subject";
  map = "https://downloads.ahbl.org/rspamd/ahbl-spamsigns-subject.map.zst";
  regexp = true;
  description = "AHBL: Spam signs in subject";
}

AHBL_SPAM_EMAIL_FROM {
	type = "from";
	map = "https://downloads.ahbl.org/rspamd/ahbl-spam-email-addy.map.zst";
	description = "AHBL: Spam email address in From:";
}

AHBL_BADREP_DOMAINS_HEADER_FROM {
  type = "selector";
  selector = "from('mime'):domain";
  map = "https://downloads.ahbl.org/rspamd/ahbl-badrep-domains.map.zst";
  regexp = false;
  description = "AHBL: Bad reputation / spam domains in Header From";
}

AHBL_BADREP_DOMAINS_URL {
  type = "url";
  map = "https://downloads.ahbl.org/rspamd/ahbl-badrep-domains.map.zst";
  regexp = false;
  description = "AHBL: Bad reputation / spam domains in URLs";
}