# Modular multimap loader.
# Rules are split into local.d/nforcer/*.conf and maps are stored in maps.d/.

.include(try=true,priority=1,duplicate=merge) "https://raw.githubusercontent.com/nforceroh/rspamd_config/refs/heads/main/local.d/multimap.conf"
