# Fuzzy hashing module configuration
# https://rspamd.com/doc/modules/fuzzy_check.html

# Global settings
min_bytes = 1k;
timeout = 2s;
retransmits = 1;
hash_alg = "mumhash";

# Rspamd.io upstream fuzzy storage
rule "rspamd.io" {
  servers = "127.0.0.1:11335";
  read_only = true;
  skip_unknown = true;

  checks = {
    text {
      enabled = true;
      min_length = 32;
      short_text_direct_hash = true;
    }
    html {
      enabled = true;
      min_html_tags = 15;
    }
    image {
      enabled = true;
      min_width = 32;
      min_height = 32;
    }
    archive {
      enabled = true;
    }
  }

  fuzzy_map = {
    RSPAMDIO_FUZZY_DENIED {
      flag = 1;
      max_score = 20.0;
    }
    RSPAMDIO_FUZZY_PROBABLE {
      flag = 2;
      max_score = 10.0;
    }
  }
}

# Local fuzzy storage
rule "LOCAL" {
  servers = "127.0.0.1:11335";
  read_only = false;
  skip_unknown = true;

  checks = {
    text {
      enabled = true;
      min_length = 32;
      short_text_direct_hash = true;
    }
    html {
      enabled = true;
      min_html_tags = 15;
    }
    image {
      enabled = true;
      min_width = 32;
      min_height = 32;
    }
    archive {
      enabled = true;
    }
  }

  fuzzy_map = {
    LOCAL_FUZZY_DENIED {
      flag = 11;
      max_score = 20.0;
    }
    LOCAL_FUZZY_PROB {
      flag = 12;
      max_score = 10.0;
    }
    LOCAL_FUZZY_WHITE {
      flag = 13;
      max_score = 5.0;
    }
  }
}
