key_prefix = "rs_history"; # Default key name
nrows = 2000; # Default rows limit
compress = true; # Use zstd compression when storing data in Redis
subject_privacy = false; # subject privacy is off
expire = 7776000; # Expire in seconds for inactive keys, default to 90 days
