# /etc/rspamd/local.d/metadata_exporter.conf

rules {
  MAILGALLOWS_INGEST {
    backend = "http";
    url = "http://${MAILGALLOWS_HOST}:${MAILGALLOWS_PORT}/quarantine";
    selector = "is_reject";
    formatter = "default";
    
    # --- HOTFIX: Replaces the deprecated 'meta_headers = true' option ---
    format = "multipart";
  }
}
