# Show all symbols including zero-score ones
extended_urls = true;

# Include actions configuration
actions {
  .include(try=true,priority=1,duplicate=merge) "$CONFDIR/local.d/actions.conf"
}

subject = "*** SPAM *** %s";
symbols {
	"PHISHING_DATABASE" {
		description = "Matched external phishing database";
		score = 8.0;
	}
  "ENCRYPTED_CHAT" {
    score = -20.0;
  }
}

group "bayes" {
	symbol "BAYES_SPAM" {
		weight = 7.5;
		description = "Message probably spam, probability: ";
	}
	symbol "BAYES_HAM" {
		weight = -2.5;
		description = "Message probably ham, probability: ";
	}
}

symbol "MIME_BASE64_TEXT" {
  score = 2.5;
  description = "Penalize obfuscated text parts";
}