#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ]; then
	set -x
	DEBUG_ARG="--debug" 
fi

echo ''
echo '** Starting rspamd'
exec /usr/bin/rspamd --user rspamd --group rspamd --no-fork $DEBUG_ARG