#!/command/with-contenv bash

### Set Defaults
ADMIN_PASS=${ADMIN_PASS:-"admin"}
CLAMAV_HOST=${CLAMAV_HOST:-"clamav"}
CLAMAV_PORT=${CLAMAV_PORT:-"3310"}
DCC_HOST=${DCC_HOST:-"dcc-svc"}
DCC_PORT=${DCC_PORT:-"10045"}
REDIS_HOST=${REDIS_HOST:-"redis"}
REDIS_PORT=${REDIS_PORT:-"6379"}
REDIS_DB=${REDIS_DB:-"7"}
REDIS_TIMEOUT=${REDIS_TIMEOUT:-"1.0"}
LOG_LEVEL=${LOG_LEVEL:-"info"} # error,warning,info,debug

### Copy rspamd configuration files
echo "Copying rspamd configuration files..."
cd /assets/rspamd
tar cvf - . | tar xvf - -C /etc/rspamd/
echo "Configuration files copied."

### Set Password
sed -i "s/password = .*/password = \"${ADMIN_PASS}\";/" /etc/rspamd/local.d/worker-controller.inc

### Set Log Level
sed -i "s/level = .*/level = \"${LOG_LEVEL}\";/" /etc/rspamd/local.d/logging.inc

### Setup Redis
cat <<EOF > /etc/rspamd/local.d/redis.conf
servers = "$REDIS_HOST:$REDIS_PORT";
db = "$REDIS_DB";
write_servers = "$REDIS_HOST:$REDIS_PORT";
read_servers = "$REDIS_HOST:$REDIS_PORT";
timeout = $REDIS_TIMEOUT;
EOF

# Clamav
sed -i "s/servers = .*/servers = \"${CLAMAV_HOST}:${CLAMAV_PORT}\";/" /etc/rspamd/local.d/antivirus.conf

# DCC
sed -i "s/servers = .*/servers = \"${DCC_HOST}:${DCC_PORT}\";/" /etc/rspamd/local.d/dcc.conf

# if [ "$PLUGIN_DKIM" = "TRUE" ] || [ "$PLUGIN_DKIM" = "true" ];  then
# 	if [ ! -d /var/lib/rspamd/dkim ]; then
# 		mkdir -p /var/lib/rspamd/dkim
# 	fi
# 	if [ ! -e /var/lib/rspamd/dkim/dkim.key ]; then
# 		rspamadm dkim_keygen -b 2048 -s dkim -k /var/lib/rspamd/dkim/dkim.key > /var/lib/rspamd/dkim/dkim.txt
# 	fi
# 	chmod 440 /var/lib/rspamd/dkim/*
# cat <<EOF> /etc/rspamd/local.d/dkim_signing.conf
# selector = "mail";
# path = "/var/lib/rspamd/dkim/\${selector}.key";
# allow_username_mismatch = true;
# EOF
# 	cp -R /etc/rspamd/local.d/dkim_signing.conf /etc/rspamd/local.d/arc.conf
# fi 

#FEATURES_ENABLED=`set -o posix; set | sort | grep PLUGIN | grep TRUE |sed -e 's/PLUGIN_//g' | sed -e 's/=TRUE//g' | awk -vRS="" -vOFS=', ' '$1=$1' | tr A-Z a-z`
#echo '** [rspamd] Enabling the following features: '$FEATURES_ENABLED

### Setup Persistent Storage
if [ ! -d /run/rspamd ]; then
	mkdir -p /run/rspamd
fi

chown -R rspamd:rspamd /var/lib/rspamd /etc/rspamd /run/rspamd

mkdir -p /tmp/state
touch /tmp/state/rspamd-init

echo "rspamd modifications completed"
